// @ts-nocheck
'use strict'; // code generated by pbf v3.2.1
// ArticleList ========================================

export var ArticleList = self.ArticleList = {};

ArticleList.read = function (pbf, end) {
    return pbf.readFields(ArticleList._readField, {listOfArticles: []}, end);
};
ArticleList._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.listOfArticles.push(Article.read(pbf, pbf.readVarint() + pbf.pos));
};
ArticleList.write = function (obj, pbf) {
    if (obj.listOfArticles) for (var i = 0; i < obj.listOfArticles.length; i++) pbf.writeMessage(1, Article.write, obj.listOfArticles[i]);
};

// Article ========================================

export var Article = self.Article = {};

Article.read = function (pbf, end) {
    return pbf.readFields(Article._readField, {uuid: "", title: "", url: "", tags: ""}, end);
};
Article._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.uuid = pbf.readString();
    else if (tag === 2) obj.title = pbf.readString();
    else if (tag === 3) obj.url = pbf.readString();
    else if (tag === 4) obj.tags = pbf.readString();
};
Article.write = function (obj, pbf) {
    if (obj.uuid) pbf.writeStringField(1, obj.uuid);
    if (obj.title) pbf.writeStringField(2, obj.title);
    if (obj.url) pbf.writeStringField(3, obj.url);
    if (obj.tags) pbf.writeStringField(4, obj.tags);
};
